move_1:
  ros__parameters:
    plugins:
      - plansys2_move_nc_node
    waypoints: ["bedroom", "gym", "kitchen", "livingroom", "bathroom"]
    waypoint_coords:
      gym: [1.13, 3.70, 0.00]
      bedroom: [-6.22, 0.00, 0.00]
      kitchen: [6.19, -2.83, 0.00]
      livingroom: [0.00, 0.00, 0.00]
      bathroom: [-5.26, -3.56, 0.00]

transport_1:
  ros__parameters:
    plugins:
      - plansys2_close_gripper_nc_node
      - plansys2_open_gripper_nc_node
      - plansys2_move_nc_node
      - plansys2_approach_object_nc_node
    waypoints: ["bedroom", "gym", "kitchen", "livingroom", "bathroom"]
    waypoint_coords:
      gym: [1.13, 3.70, 0.00]
      bedroom: [-6.22, 0.00, 0.00]
      kitchen: [6.19, -2.83, 0.00]
      livingroom: [0.00, 0.00, 0.00]
      bathroom: [-5.26, -3.56, 0.00]

open_1:
  ros__parameters:
    plugins:
      - plansys2_open_door_nc_node
  
