name: main-test
on:
  - pull_request
  - push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:humble-desktop
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y wget python3-vcstool python3-colcon-coveragepy-result
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.3.0
        with:
          package-name: plansys2_nc_bt
          target-ros2-distro: humble
          import-token: ${{ secrets.TEST_WORKFLOWS }}
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
